# Generated by Django 5.2.4 on 2025-08-13 12:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetimage',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude in decimal degrees', null=True),
        ),
        migrations.AlterField(
            model_name='streetimage',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geographic point location', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='streetimage',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude in decimal degrees', null=True),
        ),
    ]
