# Generated by Django 5.2.4 on 2025-08-19 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0002_alter_streetimage_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='streetimage',
            name='altitude_ref',
            field=models.CharField(blank=True, help_text='Altitude reference (sea level/below)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='camera_make',
            field=models.CharField(blank=True, help_text='Camera manufacturer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='camera_model',
            field=models.CharField(blank=True, help_text='Camera model', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='camera_serial',
            field=models.CharField(blank=True, help_text='Camera serial number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='color_space',
            field=models.CharField(blank=True, help_text='Color space', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='compression',
            field=models.CharField(blank=True, help_text='Compression type', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='date_time_digitized',
            field=models.DateTimeField(blank=True, help_text='Digitized date/time', null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='date_time_original',
            field=models.DateTimeField(blank=True, help_text='Original date/time', null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='exposure_mode',
            field=models.CharField(blank=True, help_text='Exposure mode', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='exposure_time',
            field=models.CharField(blank=True, help_text='Exposure time (e.g., 1/125)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='f_number',
            field=models.FloatField(blank=True, help_text='Aperture f-number', null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='flash',
            field=models.CharField(blank=True, help_text='Flash setting', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='focal_length',
            field=models.FloatField(blank=True, help_text='Focal length in mm', null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='focal_length_35mm',
            field=models.FloatField(blank=True, help_text='35mm equivalent focal length', null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='gps_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='gps_img_direction',
            field=models.FloatField(blank=True, help_text='Image direction', null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='gps_img_direction_ref',
            field=models.CharField(blank=True, help_text='Image direction reference', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='gps_speed',
            field=models.FloatField(blank=True, help_text='GPS speed in km/h', null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='gps_track',
            field=models.FloatField(blank=True, help_text='Direction of movement', null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='image_height',
            field=models.IntegerField(blank=True, help_text='Image height in pixels', null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='image_width',
            field=models.IntegerField(blank=True, help_text='Image width in pixels', null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='iso_speed',
            field=models.IntegerField(blank=True, help_text='ISO speed rating', null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='lens_make',
            field=models.CharField(blank=True, help_text='Lens manufacturer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='lens_model',
            field=models.CharField(blank=True, help_text='Lens model', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='orientation',
            field=models.IntegerField(blank=True, help_text='Image orientation (1-8)', null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='pitch',
            field=models.FloatField(blank=True, help_text='Camera pitch/tilt in degrees', null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='pixel_x_dimension',
            field=models.IntegerField(blank=True, help_text='Pixel X dimension', null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='pixel_y_dimension',
            field=models.IntegerField(blank=True, help_text='Pixel Y dimension', null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='roll',
            field=models.FloatField(blank=True, help_text='Camera roll in degrees', null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='sensor_height',
            field=models.FloatField(blank=True, help_text='Sensor height in mm', null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='sensor_width',
            field=models.FloatField(blank=True, help_text='Sensor width in mm', null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='software',
            field=models.CharField(blank=True, help_text='Software used', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='white_balance',
            field=models.CharField(blank=True, help_text='White balance setting', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='streetimage',
            name='yaw',
            field=models.FloatField(blank=True, help_text='Camera yaw/heading in degrees', null=True),
        ),
        migrations.AddIndex(
            model_name='streetimage',
            index=models.Index(fields=['camera_make', 'camera_model'], name='project_api_camera__d5c0a3_idx'),
        ),
    ]
