# Generated by Django 5.2.4 on 2025-08-22 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0003_streetimage_altitude_ref_streetimage_camera_make_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerrainModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('terrain_type', models.CharField(choices=[('DEM', 'Digital Elevation Model'), ('DSM', 'Digital Surface Model'), ('DTM', 'Digital Terrain Model')], default='DEM', max_length=10)),
                ('file_type', models.CharField(choices=[('tif', 'GeoTIFF'), ('tiff', 'GeoTIFF'), ('asc', 'ASCII Grid'), ('xyz', 'XYZ Grid')], default='tif', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('s3_file_key', models.CharField(help_text='S3 key/path for the terrain file', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('crs', models.CharField(blank=True, max_length=100, null=True)),
                ('bounding_box', models.JSONField(blank=True, null=True)),
                ('pixel_size', models.JSONField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('min_elevation', models.FloatField(blank=True, null=True)),
                ('max_elevation', models.FloatField(blank=True, null=True)),
                ('elevation_unit', models.CharField(default='meters', max_length=20)),
                ('geoserver_layer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('geoserver_url', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('group_tag', models.ManyToManyField(blank=True, to='project_api.rastergrouptag')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrain_models', to='project_api.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Terrain Models',
                'ordering': ['-uploaded_at'],
                'unique_together': {('project', 'file_name')},
            },
        ),
    ]
