# Generated by Django 5.2.4 on 2025-08-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0004_terrainmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasterlayer',
            name='geoserver_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='terrainmodel',
            name='geoserver_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vectorlayer',
            name='geoserver_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
