# Generated by Django 5.2.4 on 2025-07-28 11:17

import kampas_be.company_api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(default=company_api.models.generate_unique_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
                ('licence_type', models.CharField(choices=[('Individual', 'Individual'), ('Proffetional', 'Proffetional'), ('Enterprises', 'Enterprises')], default='Proffetional', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pin', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('primary_contact', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(default=company_api.models.generate_unique_id, editable=False, max_length=25, primary_key=True, serialize=False)),
                ('client_type', models.CharField(choices=[('Individual', 'Individual'), ('Business', 'Business'), ('Other', 'Other')], default='Individual', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('primary_contact_number', models.CharField(blank=True, max_length=20)),
                ('secondary_contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pin', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_clients', to=settings.AUTH_USER_MODEL)),
                ('client_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_client', to='company_api.company')),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_clients', to='company_api.company')),
            ],
            options={
                'unique_together': {('owner_company', 'client_company')},
            },
        ),
    ]
